### ISSUE TITLE
Is fable/elmish compatible with third party Vue components?

### ISSUE THREAD

**Issue by badgh** [fable-compiler/fable-elmish#213]
Almost everywhere in the docs, the elmish book, only react components are discussed. Especially, since React is used as an underlying rendering engine. What about vuejs? Is it possible to use vuejs components in elmish projects?

**Comment by MangelMaxime** [comment]
Hello @badgh,

the core of Elmish is about managing the State and updating it. It is agnostic to the renderer used.

For example, Elmish is known to be used with VirtualDom (original v dom library), React, Preact, Snabbdom, no Gui, Terminal GUI, Xamarin, WPF, etc.

So in theory, you can use Elmish with Vue.js or any rendering library is you write the `Program.withVueJs` to register the Vue.JS render function and allow Elmish to call it every time the State change.

Most people use React because when creating Elmish, React has been where the community put its effort in especially for the rich ecosystem. Also, Vue.JS at that time wasn't yet in the SPA with a single State philosophy that it can have now.
