### ISSUE TITLE
Decouple runWith() from RingBuffer - Proposal

### ISSUE THREAD

**Issue by xloggr** [fable-compiler/fable-elmish#215]
### Description

When experimenting with Elmish subscriptions, I wrote a sample app based on this [example](https://elmish.github.io/elmish/subscriptions.html) (adapted for CLR):

```
open Elmish

type Model = int
type Msg = | Tick
let init () = 0, Cmd.none

let update msg model =
    match msg with
    | Tick ->
        model, Cmd.none

let timer _ =
    let rec tick dispatch =
        async {
            do! Async.Sleep 1000
            dispatch Tick
            do! tick dispatch
        }
    tick >> Async.Start |> Cmd.ofSub

[<EntryPoint>]
let main argv =
    Program.mkProgram init update (fun model -> printfn "%A" model)
    |> Program.withSubscription timer
    |> Program.run
    0 // return an integer exit code
```

### Expected Behavior

I expected the app to generate a Tick message every second and print the model. Instead, it only printed the model once and then exited. I haven't tested it with Fable, but based on this [example](https://elmish.github.io/elmish/subscriptions.html) I assume the app somehow kept running.

After looking at the `program.fs` source code I realized that `runWith()` function exits once all messages stored in the `RingBuffer` instance are processed. Apparently, it is assumed that commands generated by `init()` and `update()` functions will keep producing messages as long as an application is expected to run.

To keep the sample app from exiting prematurely, I had to introduce a "KeepAlive" message to be returned by both `init()` and `update()` functions. This, however, is not very efficient, causing the app to waste CPU resources while waiting for the next timer tick. It'd be nice if the app could efficiently wait for subscription-generated messages when there is nothing else to do.

In addition, I noticed that `runWith()` is tightly coupled with `RingBuffer`. Factoring it out will enable developers to provide their own buffer implementations. Among other things, it will facilitate program loop testing and enable controlling the loop exit condition.

### Proposed Solution

Here is a proposed implementation:
```
    [<AbstractClass>]
    type MessageBuffer<'msg>() =
        abstract member Push : 'msg -> unit
        abstract member Pop : unit -> 'msg option    // program loop will exit, once this method returns None

    // Helper function used in runWith*MessageBuffer() functions
    // Dispatches initial commands generated by init() and subscribe() functions.
    // Returns initial model
    let private initProgram dispatch (arg: 'arg) (program: Program<'arg, 'model, 'msg, 'view>) =
        let (model,cmd) = program.init arg
        program.setState model dispatch
        let sub = 
            try 
                program.subscribe model 
            with ex ->
                program.onError ("Unable to subscribe:", ex)
                Cmd.none
        Cmd.batch [sub; cmd]
        |> Cmd.exec (fun ex -> program.onError ("Error intitializing:", ex)) dispatch
        model

    // Helper function used in runWith*MessageBuffer() functions
    // Handles the specified message
    // Returns update model (upon success) or unchanged model (upon error)
    let private handleMessage model dispatch program msg =
        try
            let (model',cmd') = program.update msg model
            program.setState model' dispatch
            cmd' 
            |> Cmd.exec (fun ex -> program.onError (sprintf "Error in command while handling: %A" msg, ex)) dispatch
            model'
        with ex ->
            program.onError (sprintf "Unable to process the message: %A" msg, ex)
            model

    /// Start the program loop. The loop will terminate once buf.Pop() returns None.
    /// buf: external message buffer.
    /// arg: argument to pass to the init() function.
    /// program: program created with 'mkSimple' or 'mkProgram'.
    let runWithMessageBuffer (buf: MessageBuffer<'msg>) (arg: 'arg) (program: Program<'arg, 'model, 'msg, 'view>) =
        let syncDispatch = program.syncDispatch buf.Push

        let rec loop model =
            let nextMsg = buf.Pop()
            if nextMsg.IsSome then
                nextMsg.Value
                |> handleMessage model syncDispatch program
                |> loop
      
        initProgram syncDispatch arg program |> loop
```

now `runWith()` can be reimplemented as follows:

    let runWith (arg: 'arg) (program: Program<'arg, 'model, 'msg, 'view>) =
        let rb = RingBuffer 10
        let buf = {
            new MessageBuffer<'msg>() with
                override __.Push(msg) = rb.Push(msg)
                override __.Pop() = rb.Pop()
        }
        runWithMessageBuffer buf arg program

This approach has the following advantages:
- no mutable state within `runWith()` function (`reentered` and `state` vars in the current code); all side-effects are encapsulated within `MessageBuffer` methods;
- reduced coupling (buffer implementation is provided, rather than hard-coded - see [Dependency inversion principle](https://en.wikipedia.org/wiki/Dependency_inversion_principle));
- backward-compatible with the original implementation, so existing code will require no changes;
- enables providing mock buffer implementation, facilitating unit testing.

One noteworthy difference from the original code is, that in the current implementation incoming messages are buffered only 
if another message is being processed (`reentered = true`), otherwise they are processed right away.
In the proposed implementation messages are always buffered before processing. It may slightly increase message processing time in some cases. This, however, is probably a small price to pay for convenience and may be acceptable in most scenarios. 

Getting back to the sample app, it will be possible to implement a custom `runSampleApp()` method as follows:
```
    let runSampleApp (program: Program<'arg, 'model, 'msg, 'view>) =
        let q = SomeBlockingFIFOQueue<'msg>()
        let buf = {
            new Program.MessageBuffer<'msg>() with
                override __.Push(msg) = q.Enqueue(msg)
                override __.Pop() = q.Dequeue() |> Some    // Dequeue() will block until a message is available
        }
        Program.runWithMessageBuffer buf arg program
```
To enable graceful termination, the buffer implementation can cause `Pop()` to return `None` when exit condition is met.

---

A further extension of the suggested approach is to provide an async version of the `runWith*()` function:
```
    [<AbstractClass>]
    type AsyncMessageBuffer<'msg>() =
        abstract member Push : 'msg -> unit
        abstract member Pop : unit -> Async<'msg option>

    /// Start the program loop asynchronously. The loop will terminate once buf.Pop() returns None.
    let runWithMessageBufferAsync (buf: AsyncMessageBuffer<'msg>) (arg: 'arg) (program: Program<'arg, 'model, 'msg, 'view>) = async {
        let syncDispatch = program.syncDispatch buf.Push

        let rec loop model = async {
            let! nextMsg = buf.Pop()
            if nextMsg.IsSome then
                return! nextMsg.Value
                |> handleMessage model syncDispatch program
                |> loop
        }
      
        do! initProgram syncDispatch arg program |> loop
    }
```

For example, here is how a program can run within a MailboxProcessor:
```
    let runInMailboxProcessor (arg: 'arg) (program: Program<'arg, 'model, 'msg, 'view>) =
        MailboxProcessor<'msg>.Start(fun inbox -> 
            let buf = {
                new Program.AsyncMessageBuffer<'msg>() with
                    override __.Push(msg) = inbox.Post(msg)
                    override __.Pop() = async { 
                        let! msg = inbox.Receive() 
                        return Some msg 
                    }
            }
            Program.runWithMessageBufferAsync buf arg program
        )
```

### Feedback
I'll appreciate you feedback on this proposal.

You can see the updated [`program.fs`](https://github.com/xloggr/elmish/blob/run-with-buffer/src/program.fs) in the private fork of this repo I created for use in my own projects, and the diff from the origin is available [here](https://github.com/xloggr/elmish/pull/1). If you find it acceptable and useful, I'll be glad to send a PR.

### Related information 

* elmish version: 3.1.0
* fable-compiler version: N/A
* fable-core version: N/A
* Operating system: Windows, Linux

**Comment by et1975** [comment]
I was waiting for other perspectives, but if there are no comments I'll go ahead...

First of, thanks for a thoughtful proposal!

As you have deduced the "loop" is not really a loop but an infinite chain of callbacks. No events - no action. This is the lowest cost system from cpu/performance perspective. 

The early exit is easy to prevent, if the main thread is not needed after `run` then why not just `Thread.Sleep Infinite`, but I think it's helpful to analyze the situation from these perspectives:
- Which thread is the "loop" executing on and/or what is the expected concurrency inside of it.
- What are the desirable and observable runtime characteristics of parallelism.

With that in mind, the queueing mechanism (if any) is the implementation detail of the loop. As boundaries go, Push/Pop interface is not something elmish should present to the world as it says absolutely nothing about the allowed threading or blocking behavior.

Current implementation works for both JS (single-threaded) and WPF (STA multithreaded) worlds, but originally it was a beautifully simple, but unfortunately incorrect [mailbox implementation](https://github.com/elmish/elmish/blob/v0.8.x/src/elmish/elmish.fs#L132). Ever since the effort has been made to tighten `Program` abstraction and let one implement the loop in its entirety the way one needs it while benefitting from the rest. 

Having said that, I don't think the current loop implementation is particularly great (it's just correct), the way it defines termination is a bit wishy-washy, and in general I'm open to `Program` abstraction adjustments to make implementing new loops easier. At least I think that's where the value is.

**Comment by xloggr** [comment]
@et1975, thank you for your feedback.

Unfortunately, adding `Thread.Sleep` call after invoking `run` won't help: after `run` call has exited, there will be no running loop to dispatch messages generated by the timer subscription. A blocking call should be somewhere within the `run*` function to keep it from exiting.

In your comment you said
> Ever since the effort has been made to tighten Program abstraction and let one ***implement the loop in its entirety the way one needs*** it while benefitting from the rest.

If it was possible, I would be glad to do just that. Indeed, my first thinking was to implement a custom `myRunWith` function with an alternative (blocking) message queueing mechanism. Unfortunately, it was not possible, because the `Program` record is private. `Program.map` function didn't help either, as it doesn't provide access to some of the `Program` record fields. That's why I came up with an alternative approach.

I get your concern about unnecessarily exposing message queueing mechanism. In my proposal it remains hidden for developers using `runWith` and `run` functions, and they won't need to implement `Pop`/`Push` methods. The change is fully backward-compatible, both syntactically and semantically. However, if a customization is required, `runWithMessageBuffer` can be used. 

As for `MailboxProcessor`, it naturally comes to mind when implementing an "async message loop". However, in my opinion introducing it as an Elmish library dependency is unnecessary, and the suggested approach is, in fact, more flexible. Having the proposed `runWithMessageBufferAsync` function in the library, one can use `MailboxProcessor` (as shown in the example), or any alternative "async message loop runner" - as found suitable by an application developer using Elmish.

**Comment by TysonMN** [comment]
I am inclined to agree with @et1975.

@xloggr, if the code you have in mind is easy to write, then I suggest you write it.  Then we can all look at it together.  It is much easier to discuss these things when considering a specific example.

**Comment by et1975** [comment]
> Unfortunately, adding Thread.Sleep call after invoking run won't help: after run call has exited, there will be no running loop to dispatch messages generated by the timer subscription. A blocking call should be somewhere within the run* function to keep it from exiting.

Can you demonstrate that? I fail to see how exiting `run` invalidates the callback handlers.

**Comment by xloggr** [comment]
@et1975, I stand corrected. I've run an additional test, and indeed, adding `Thread.Sleep` does keep subscription working.

When I just started playing with Elmish, I somehow managed to get the result I described in the original post, and quickly came to a wrong conclusion that subscriptions work only as long as `run` is, well, running ;).
Thank you for helping me to get it right!

The proposal still have a merit in terms of cleaner code (stateless, reduced coupling) and improved testability (message buffer can be mocked), so I hope it is worth considering.

**Comment by xloggr** [comment]
@TysonMN, there are a couple of examples using the proposed `runWithMessageBuffer*` functions in the original issue post. Please see `runSampleApp` and `runInMailboxProcessor` above, as well as reimplemented `runWith`.

**Comment by TysonMN** [comment]
I am confused with the difference between your OP and what you still think is worth changing now that adding `Thread.Sleep` works as @et1975 suggested.

Can you create and share a branch that changes the code in a way that you think makes it better?

**Comment by xloggr** [comment]
@TysonMN, I've already done it and shared the link in my original post.
Here's the direct [link](https://github.com/xloggr/elmish/blob/run-with-buffer/src/program.fs) to the updated `program.fs`. And here is the [diff](https://github.com/xloggr/elmish/pull/1/files).

**Comment by et1975** [comment]
Thanks again for the proposal, but with the original problem out of the way I'm going to decline the design changes - the coupling of the loop and the queue is intentional as the latter is the implementation detail of the former.

**Comment by TysonMN** [comment]
> @TysonMN, I've already done it and shared the link in my original post.
> Here's the direct [link](https://github.com/xloggr/elmish/blob/run-with-buffer/src/program.fs) to the updated `program.fs`. And here is the [diff](https://github.com/xloggr/elmish/pull/1/files).

Thanks for sharing those links again.  I didn't notice them in your OP.

[I reviewed your PR](https://github.com/xloggr/elmish/pull/1#pullrequestreview-593436107) a bit.

Can you also link to code (as in, an entire application; executable code) that uses your alternative implementation to achieve your desired behavior?  I will review again after taking a close look at that code.

-------

> Apparently, it is assumed that commands generated by `init()` and `update()` functions will keep producing messages as long as an application is expected to run.

That is not true.  You are forgetting about the view.  It can also dispatch messages; no commands needed.

That is why the function
https://github.com/elmish/elmish/blob/87fb741fdbecbfd58ece6e171d376afcd8de62ee/src/program.fs#L39-L42

is useful: because it is possible to create a nontrivial application even without using commands.

For concrete examples, see [Elmish.WPF](https://github.com/elmish/Elmish.WPF) and especially the [samples](https://github.com/elmish/Elmish.WPF/tree/master/src/Samples).  The simplest sample is [`SimpleCounter`](https://github.com/elmish/Elmish.WPF/tree/master/src/Samples/SingleCounter).  Its `init` and `update` functions do not return commands.  And yet, the application could execute forever is useful for introducing people to Elmish.WPF.

--------

> It'd be nice if the app could efficiently wait for subscription-generated messages when there is nothing else to do.

I want to make sure we are on the same page about this.  As @et1975 said in https://github.com/elmish/elmish/issues/215#issuecomment-780133865...
> As you have deduced the "loop" is not really a loop but an infinite chain of callbacks. No events - no action. This is the lowest cost system from cpu/performance perspective.

...the current implementation is already maximizing efficiency.  As you said in the OP...
> One noteworthy difference from the original code is, that in the current implementation incoming messages are buffered only
if another message is being processed (reentered = true), otherwise they are processed right away.
In the proposed implementation messages are always buffered before processing. It may slightly increase message processing time in some cases.

...your proposal will reduce efficiency.

**Comment by xloggr** [comment]
> I reviewed your PR a bit.

@TysonMN, thank you for taking time to review my code. You brought up some good points that I will take into account.

> That is not true. You are forgetting about the view. It can also dispatch messages; no commands needed.

I started using Elmish at the first place because I liked MVU approach in general, and it appeared appropriate for my app. However, the app has no UI and I didn't plan to use the `view` part. Nevertheless, even though I am not familiar with WPF, looking at the samples helped me to understand how to organize my code using an unmodified version of Elmish, so I will rework my app.

Anyway, it was an interesting exercise and I feel I now better understand Elmish.
@et1975, @TysonMN - thank you for your feedback.

**Comment by TysonMN** [comment]
> However, the app has no UI and I didn't plan to use the `view` part. Nevertheless, even though I am not familiar with WPF, looking at the samples helped me to understand how to organize my code using an unmodified version of Elmish, so I will rework my app.

That is great to hear.

Elmish.WPF is an interesting use of Elmish because unlike a traditional MVU application, the view is not dynamically created from each new copy of the model.  The views are statically defined, the (Elmish) view function is not used, the first call to the (Elmish) `setState` function caches a reference to the `dispatch` function as well as initializes many other caches, and each additional call to `setState` updates those caches as well as raises the notifications that WPF expect when there are changes.

Although I have never done so, I think it should be possible to make an MVU application (say with Elmish) without a _user_ interface.  Instead, the "view" would be the _application programming_ interface used by other programs.  An incoming REST call could dispatch a message, which could start a sequence of command creations, which would finally result in a command that sends a response.  Normally some of the information in such a request is implicitly cached on the call stack.  In this approach, that information must be explicitly passed around as the response is being created.
