### ISSUE TITLE
Does not build on Windows

### ISSUE THREAD

**Issue by davidpodhola** [fable-compiler/fable-elmish#22]
When I cloned the repo, it does not build on my machine where otherwise [I use fable](http://www.naseukoly.cz/blog/2016/12-20-hello-fable-import-sharepoint/index.html).

I am pretty sure it is because I miss something and generally I am too pedantic on the DevOps (does that still exist?).

	Building: C:\Users\david.podhola\Documents\S\fable-elmish\src\elmish
	C:\Users\david.podhola\Documents\S\fable-elmish\packages\Npm.js\tools\npm.cmd run build
	Running build failed.
	Error:
	System.Exception: Start of process C:\Users\david.podhola\Documents\S\fable-elmish\packages\Npm.js\tools\npm.cmd failed. The system cannot find the file specified

![capture](https://cloud.githubusercontent.com/assets/436605/21865127/12a7eb68-d845-11e6-8c11-e7cd5c6bd422.PNG)

**Comment by et1975** [comment]
That's true, the build infrastructure is weak ATM and it doesn't build on Windows. 
Partially because I use OSX and partially because I don't believe paket should be installing npm as my local dependency. Also, I've switched a while ago to yarn, so even if it worked, it wouldn't be doing a proper job, i.e. a reproducible build.

Having said that, running `yarn build` in each of `src` subfolders (starting with `elmish`) should build on Windows (it did, last time I tried).

Thanks for bringing it to my attention again, I need to have a better build script and Travis/AppVeyor to go with it.

**Comment by MangelMaxime** [comment]
We was having the same problem for fable-arch.
If you upgrade Fake to a certain version, them it will look for `npm.bat` in your `PATH` variable.

Here is the commit fixing the problem for Fable-arch: https://github.com/fable-compiler/fable-arch/commit/9aaf39de6f2aa30db71871634b3d5fafd8027353

**Comment by davidpodhola** [comment]
Thanks @et1975 . Yes, I also do not believe `npm` should be installed locally. I have `npm` installed, but for some reason it is not detected by `FAKE` (?)

Anyway in samples it seems `cp` is used so it would not run anyway even with `yarn` I assume.

**Comment by et1975** [comment]
> cp is used 
Ah, yes... unless `cp` is an alias in PowerShell? Can't wait for linux subsystem to become mainstream on Windows :)

Anyway, even as it is, it's easy to fix - since all the web samples use webpack2 it would be fairly straightforward to either pack the styles from the `node_modules` or add a plugin to do the copying.

**Comment by davidpodhola** [comment]
OK, [thanks for the info](https://github.com/fable-compiler/fable-elmish/issues/22#issuecomment-271992772) will have a look at that next week.

**Comment by et1975** [comment]
If you check my fork, you'll see I've switched the build to `yarn`, it builds on AppVeyor and TravisCI now. Got into a weird Fable build problem trying to consolidate dev dependencies, but fake script is fine now.
The samples take a long time to build, so I'll keep them as an optional target. Still would like to see them building on Windows, so I'd appreciate the effort there!

**Comment by et1975** [comment]
The elmish projects should build now (see the updated readme).

**Comment by davidpodhola** [comment]
`build.cmd` without parameters works now, great, thank you @et1975! 
samples [do not build](https://github.com/fable-compiler/fable-elmish/issues/22#issuecomment-271992772); it is not only matter of `cp`, there are other path-related issues I think.

Will need to look at this more

![capture](https://cloud.githubusercontent.com/assets/436605/22038576/0bba7904-dcfc-11e6-86d6-64e9580178d1.PNG)

**Comment by et1975** [comment]
that was an error in fable-elmish-react@0.8.1, please upgrade to 0.8.2.

**Comment by davidpodhola** [comment]
Confirm, after upgrade it works. Now I try to test the react native samples on Windows too, but I think this is a different story so closing here, thanks again!
