### ISSUE TITLE
Subscribe to DOM events via `Program.withSubscription`

### ISSUE THREAD

**Issue by sumeetdas** [fable-compiler/fable-elmish#229]
### Description

This is more of a question than an issue with Elmish. I'm learning Elmish and was trying to add event listener 'onClick' to a button. I thought the Elmish way of doing such things would be to add a subscriber. So, I did that: 

```f#
let buttonClick initial =
    let sub dispatch = window.addEventListener("load", fun _ -> 
        let button = document.getElementById "btn1"
        button.addEventListener("onClick", fun _ -> 
            printf "yolo"
        )
    )
    Cmd.ofSub sub
```

For some reason this is not working. I also tried adding event listener to the button without listening to `load` event but still didn't work:
```f#
let buttonClick initial =
    let button = document.getElementById "btn1" 
    let sub dispatch = button.addEventListener("onClick", fun _ -> printf "yolo")
    Cmd.ofSub sub
```

I finally was able to add event listener via `prop.onClick` (I'm using Feliz as well).

I want to understand why adding subscription for listening to DOM events like `onClick` didn't work. On the other hand, listening to window events via Elmish subscriptions worked well.

### Related information 

* elmish version:
* fable-compiler version: 3.2.3
* fable-core version: 3.2.3
* Operating system: Windows 10

**Comment by MangelMaxime** [comment]
Hello @sumeetdas,

It is probable that your view is not rendered yet and so the DOM element not available to listen to. Also, your DOM elements can be remove/added by React and so the instance you are trying to attach too can have change since the last render meaning that you handler has been disposed or moved to another element.

You can listen to `window` and `document` events because those DOM elements are global and not controlled by your application view.

As you discovered the right way of handling events coming from your application is by using the HTML properties on that element. It does the same thing has when you do:

```html
<button onclick="myFunction()">A button</button>
```

**Comment by sumeetdas** [comment]
Makes sense. Thank you @MangelMaxime for the explanation.
