### ISSUE TITLE
Zaid's fromAsync Cmd

### ISSUE THREAD

**Issue by AlbertoDePena** [fable-compiler/fable-elmish#242]
Would it be possible to add Zaid's implementation? I have several projects where I keep including this. The same goes for Deferred nad AsyncMsg... 

```fsharp
let fromAsync (operation: Async<'msg>) : Cmd<'msg> =
    let delayedCmd (dispatch: 'msg -> unit) : unit =
        let delayedDispatch = async {
            let! msg = operation
            dispatch msg
        }

        Async.StartImmediate delayedDispatch

    Cmd.ofSub delayedCmd
```

**Comment by et1975** [comment]
This doesn't offer anything new and could be easier implemented via `OfAsync.perform`, which I'd actually suggest using instead because it allows for separation between async/IO interface and application messaging as well as correct point of composition for the two.

There's also an open item to re-work how subscriptions work, so that's another reason to use these kinds of functions instead of building on `Sub` directly.

**Comment by AlbertoDePena** [comment]
@et1975 

When would I use `Cmd.OfAsync.perform` or `Cmd.OfAsyncImmediate.perform`?

**Comment by et1975** [comment]
The difference is in how the computation is started, recall that `async` in F#, unlike `promise` or `task` is "cold", ie. it's a computation in potentia, ie. not running until you explicitly start it. `StartImmediate` uses current thread to start running a computation, while `Start` schedules it to run on the background thread. You decide if you want it "at some point later", or you want it to preempt anything else (at least until it hits IO API that will schedule continuation on the background thread regardless).
