### ISSUE TITLE
Proposal: port Elm's virtual dom to work with Feliz

### ISSUE THREAD

**Issue by reinux** [fable-compiler/fable-elmish#274]
Not too sure whether this should be in the Feliz repo or this one, but I'm looking at the world famous [Elm Virtual Dom](https://github.com/elm/virtual-dom) repo, and it actually looks quite manageable: a couple thousand lines of js and a few hundred lines of Elm to interface with it.

Combined with something like Sutil, we could do away with Fable.Elmish's React dependency for many projects.

**Comment by et1975** [comment]
Go nuts, but this is not the repo for it.

**Comment by reinux** [comment]
Would it be the Feliz repo?

I'm not entirely sure where it would hook into.

**Comment by MangelMaxime** [comment]
@reinux Feliz is not the repo either because Feliz aims to provide bindings for React and its ecosystem.

The place for such a project is a new repository, which means inside of your own repository or an org that you own.

**Comment by kspeakman** [comment]
@reinux The Elmish library is independent of the view technology. Usually there is the library that houses the view technology like Fable.React(.Types now?). And an integration library marries the two. Like Fable.Elmish.React or Feliz. Feliz also layers its own syntax on top of Fable.React.

I believe there was a Virtual Dom implementation before that plugged into Elmish. But it was abandoned since React exists.

A virtual dom implementation would be nice, especially if it were more Elm-like in that you don't have to pass dispatch around nor use anonymous functions for obvious JS events. e.g. Elm: `OnInput FieldName` vs `OnInput (fun e -> dispatch (FieldName e.Value))`. But it would be a large undertaking.
