### ISSUE TITLE
[Cmd.ofMsg] - always an antipattern in update?

### ISSUE THREAD

**Issue by YkTru** [fable-compiler/fable-elmish#295]
Hi, I'm still relatively new to Elmish. While reading the excellent **Elmish Book** by @Zaid-Ajaj, I came across this passage:

On this [page](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/commands/recursive-updates):

> `Cmd.ofMsg` - There is only one alternative to Cmd.ofMsg: not using this command at all inside the `update` function!
> 
> There is never a good reason to use `Cmd.ofMsg` in update because in reality it is a command that changes the control flow of the `update`.

**Disclaimer**: I use **Elmish.WPF** with static bindings, so I’m not entirely sure if this applies as-is or behaves differently in my case.

---

**Q1:** I’ve noticed a lot of code examples use `Cmd.ofMsg` in `update`—even in the Elmish Book, Elmish documentation, and other Elmish/Community code samples. Am I missing something? Are people embracing the "risk" of unwanted loops in `update`? Is it still a **strict** recommandation?

---

**Q2:** Reading this very old [thread](https://github.com/elmish/elmish/issues/170), I got the impression that I should be using `Cmd.ofFunc.*` instead of `Cmd.ofMsg` in most (all?) cases. Am I misunderstanding? Is this an outdated recommendation? If still relevant, why doesn’t the Elmish Book encourage this approach in most of its examples?

---

**Q3:** So far, I’ve been using `Cmd.ofMsg` to invoke `Msg`s like `SelectItem of Guid option` after modifying the state (I know that it's not what @Zaid-Ajaj recommend but please read until the end). For example (pseudocode): 

> When `Msg.RemoveNode` is dispatched, modify the state, then issue `Cmd.ofMsg SelectNode(previousNode)`.

This lets me select the node just before the one that was removed, so I can press again the Remove button successively.

However, after reading the caveats about `Cmd.ofMsg` in the Elmish Book, I’m unsure how to achieve this without using `Cmd.ofMsg` or `Cmd.ofFunc`. 

*I want to re-emphasize that I use **static bindings with WPF**, and I understand that I can easily remove the actually selected node then modify the `SelectedNode: Guid option` field in my model (as in my previous e.g., set it to the previous node after removing the currently selected node) **without using `Cmd.ofMsg`**.

The **problem** is that if I don’t explicitly invoke `Cmd.ofMsg SelectNode(previousNode: Guid option)` after removing the actually selected node, my `SelectedNode_Binding`—which wraps the `SelectedNode: Guid option` in my **model** and is bound to a `ListBox.SelectedItem` property in the **UI**—won’t update the UI. 

(Apologies if this is unclear. I can share some code, but I avoided doing so since Elmish itself is not specifically about WPF.)

*Additionally, I use `Cmd.ofMsg` to handle **recursive data structures** like `Tree`, where I need to call the `SelectNode` message at arbitrary depths.

---

I’d really appreciate any advice you can share on these questions. Thank you!

**Comment by MangelMaxime** [comment]
> **Q1:** I’ve noticed a lot of code examples use `Cmd.ofMsg` in `update`—even in the Elmish Book, Elmish documentation, and other Elmish/Community code samples. Am I missing something? Are people embracing the "risk" of unwanted loops in `update`? Is it still a **strict** recommandation?

On this point, it is true that using `Cmd.ofMsg DoSomething` can be avoid by extracting the code that goes into handling `DoSomething` msg in a function and doing:

```fs
let update msg model = 
	match msg with 
	| MyMsg args ... ->
		let updatedModel = 
			{ model with ... }
			|> doSomething // Call the utility function here instead of send `Cmd.ofMsg DoSomething
```

I think here it depends on personal preference, personally I happened to use `Cmd.ofMsg` in the past because it make the code easy to read in term of message. But if you don't like the idea of having a double update happening using utility function is the way to go.



> **Q2:** Reading this very old [thread](https://github.com/elmish/elmish/issues/170), I got the impression that I should be using `Cmd.ofFunc.*` instead of `Cmd.ofMsg` in most (all?) cases. Am I misunderstanding? Is this an outdated recommendation? If still relevant, why doesn’t the Elmish Book encourage this approach in most of its examples?

`Cmd.ofXXX.*` are fonctions used to execute code in a non blocking manner and when that code resolved it a message can be send back to the Elmish loop.

For example, you could use it to fetch data on your server. You ask to retrieve the data and when received the data goes back into your Elmish loop so you can handle it and add it to your model.

`Cmd.ofMsg` is a little special in does not execute non blocking code, it kind of allows your code to `jump` to a message. This is what the ressource you linked in Q1 explains.

> *I want to re-emphasize that I use **static bindings with WPF**, and I understand that I can easily remove the actually selected node then modify the `SelectedNode: Guid option` field in my model (as in my previous e.g., set it to the previous node after removing the currently selected node) **without using `Cmd.ofMsg`**.
> 
> The **problem** is that if I don’t explicitly invoke `Cmd.ofMsg SelectNode(previousNode: Guid option)` after removing the actually selected node, my `SelectedNode_Binding`—which wraps the `SelectedNode: Guid option` in my **model** and is bound to a `ListBox.SelectedItem` property in the **UI**—won’t update the UI.

To me this looks like a potential bug or limitation of `Elmish.WPF`.

I would expect that if you modify your model in a message then the UI should be updated based on that update.

From what I understand, you say that you need to:

1. Update the model 
2. Trigger a message
3. Re-update the model
4. And then now the UI is updated

Depending on if this is a bug or limitation, you will be able to take a decision on what you prefer:

1. This is a bug and you don't like `Cmd.ofMsg`, then wait for `Elmish.WPF` to be fixed or send a PR to fix and then remove `Cmd.ofMsg` usage.
2. This is a limitation and you are forced to keep using `Cmd.ofMsg`, then you don't have a choice and need to keep using `Cmd.ofMsg`
3. You don't care, and do what works for you :)

There is also the possibility, that you could add a cache buster to your model to force Elmish.WPF to re-render the view/ For example, with react we can force a re-rendering by changing the `id` property of an HTML Element or the `key` value of a ReactComponent.

```fs
type Model =	
	{
		SelectedNode: MyNode
		// each time you modify the model update that value as it force a redraw
		// I used a GUID because each time you request a new one it should be unique, but you could use a counter or whatever you want
		CacheBuster : Guid 
	}
```

I think the cache buster things should be the last resolve, but I wanted to plan the seed in case it can be of use to you.

**Comment by et1975** [comment]
Hello, you've reached the Ivory Tower, we have all the answers. :)
Proceeding to dispense some...

- No, you are not missing anything. Zaid's takes are very opinionated but
are not the official guidance. On the opposite end of the spectrum you'll
find people for whom the whole message dispatching is tiresome and would
rather encode everything in a computation expression. The dispatch
implementation enques the changes and can even change the thread it
executes on, so there's a difference between doing something yourself
inside the update and letting the dispatch handle it via the next update,
you might need both, depending on the circumstances. Personally, I find
messages uniquely capable to communicate "sideways" and "up" the
hierarchy, YMMV.

- It's there for a reason, use it if you find it convenient. The issue you
refer to was just my OCD to align all the shapes of the `Cmd` modules.
Ignore and know that it will be there for you... forever.

- As Maxime said, there might be an issue that needs addressing in the WPF
implementation or something in how you do the bindings. I'd look deeper to
understand why it's happening and w/ or not it's a problem for
you, something like this can have unexpected performance impact. If not -
you have no reason to change anything.

Cheers.

**Comment by YkTru** [comment]
Thank you for your help; this is what I was concerned about:

> there might be an issue that needs addressing in the WPF
> implementation or something in how you do the bindings.

Since Elmish.WPF community is currently sadly on life support and my understanding of its source code is limited, I might not get an answer regarding this issue anytime soon. 

Also, this issue only concern an already problematic ElmishWPF binding (the `SubModelSelectedItem` binding which - as I understand it - **recquires to use `ViewModel.CurrentModel` for recursive bindings**, so it **does not use `Model` directly**), so I guess "little hacks" might be needed anyways. 

For now, I'll follow this advice:

> This is a limitation and you are forced to keep using Cmd.ofMsg, then you don't have a choice and need to keep using Cmd.ofMsg

I'll be cautious to **only use Cmd.ofMsg in cases where it is absolutely necessary to update the UI**, where updating the model results in no changes in UI in places where it should. 

**Q:** Do you have any suggestions for how I could enforce or encourage this constraint in my code? Perhaps I could use type aliasing for `Cmd.ofMsg` to restrict it to specific scenarios, like `CmdRetriggerUISelectedItem SelectNode(n)`. Or I guess it could be better to wrap it in a function that can only dispatch the `SelectNode` message?

Currently, I might only need it for this single case (ie update SelectedItem property in the UI on recursive structure), which should make debugging any related issues much easier, I guess.

**Comment by MangelMaxime** [comment]
> **Q:** Do you have any suggestions for how I could enforce or encourage this constraint in my code? Perhaps I could use type aliasing for `Cmd.ofMsg` to restrict it to specific scenarios, like `CmdRetriggerUISelectedItem SelectNode(n)`. Or I guess it could be better to wrap it in a function that can only dispatch the `SelectNode` message?

I would just use the standard API, adding another one would just be confusing and you would have to always ask yourself which one to use.

**Comment by Zaid-Ajaj** [comment]
> Hi, I'm still relatively new to Elmish. While reading the excellent Elmish Book by @Zaid-Ajaj,

Thank you @YkTru for the kind words 🙏 

I believe @MangelMaxime pretty much summerized what I wanted to say ❤️ 

> Zaid's takes are very opinionated but are not the official guidance.

This ☝️ indeed! The book makes a general case against usage of `Cmd.ofMsg` because it is a foot gun that can be avoided but I might have made it sound scarier than it actually is 😉 

> I'll be cautious to only use Cmd.ofMsg in cases where it is absolutely necessary to update the UI, where updating the model results in no changes in UI in places where it should.

That sounds great! You understand that `Cmd.ofMsg` _can_ be risky and minimise its usage. 

> Q2: Reading this very old https://github.com/elmish/elmish/issues/170, I got the impression that I should be using Cmd.ofFunc.* instead of Cmd.ofMsg in most (all?) cases. Am I misunderstanding? Is this an outdated recommendation? If still relevant, why doesn’t the Elmish Book encourage this approach in most of its examples?

You should be using the standard library functions for sure. When I was writing the book, these library functions weren't there and when they were introduced, people couldn't agree on their naming so I focused on the concepts behind the commands and how to implement them instead.

**Comment by YkTru** [comment]
Great thank you all for your help

**Comment by kspeakman** [comment]
@YkTru Apologies for the post-close comment, but I wanted to mention the logic of using or not using `Cmd.ofMsg`.

In the WPF case, I'm guessing `Cmd.ofMsg` is a stand-in for manually triggering a re-render. Since it returns control back to the Elmish loop and executes whatever machinery WPF has wired into it.

Otherwise, it's use depends on your philosophy. I tend to use Msg to only represent the result of side effects (including user input). Therefore I will almost never use `Cmd.ofMsg`, because whatever the next step that message would invoke could just be extracted to a fn and called in the same statement. The other philosophy is using Msg to represent logical steps (in addition to side effect results), In some cases, this can make the flow of logic clearer. It's up to your taste.

There is no right and wrong here, only tradeoffs.
